# Site settings
title: Guoyang Shen
email: guoyang.shen@outlook.com
description: >-
  Welcome to my portfolio page.
baseurl: ""  # the subpath of your site, e.g., "/blog" if your site was hosted at example.com/blog
url: "https://gshen-portfolio.github.io"  # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
permalink: /:categories/:year/:month/:day/:title/
plugins:
  - jekyll-feed

# Author
author:
  name: Guoyang Shen
  email: guoyang.shen@outlook.com
